In [ ]:
!pip install --user https://s3.amazonaws.com/pytorch/whl/cu75/torch-0.1.6.post22-cp27-none-linux_x86_64.whl
!pip install https://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linex_x86_64.whl
!pip install torchvision

In [4]:
import tensorflow

In [5]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.optim as optim
torch.manual_seed(122)

In [7]:
#creating tensor

In [9]:
v = [1,2,3]
print(type(v))

<class 'list'>


In [10]:
vec_tensor=torch.Tensor(v)
print(type(vec_tensor))

<class 'torch.Tensor'>


In [12]:
matrix = [[1,2,3],[4,5,6]]
mat_tensor = torch.Tensor(matrix)
print(mat_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [13]:
x = torch.Tensor([1,2,3])
y = torch.Tensor([4,5,6])
torch.matmul(x,y)

tensor(32.)

In [15]:
x = torch.randn(64000,3,28,28)
x_reshape = x.view(32,-1,3,28,28)
print(x_reshape.shape)

torch.Size([32, 2000, 3, 28, 28])


In [16]:
#Computational Graphs

In [8]:
x = autograd.Variable(torch.Tensor([1,2,3]),requires_grad=True) # Keeps track of variable
print(x.data)

tensor([1., 2., 3.])


In [9]:
y = autograd.Variable(torch.Tensor([1,2,3]),requires_grad=True)

In [12]:
z=x+y
print(z.data)
print(z.grad_fn) #prints the operation performed on variable z

tensor([2., 4., 6.])


In [13]:
s = z.sum()
print(s.data)
print(s.grad_fn)

tensor(12.)


In [14]:
#Not breaking pytorch computations

In [15]:
x = torch.randn((2,2))
y = torch.randn((2,2))
z=x+y
print(z)

tensor([[-0.7317, -1.1116],
        [ 0.0369,  0.6772]])


In [19]:
varx = autograd.Variable(x,requires_grad=True)
vary = autograd.Variable(y,requires_grad=True)
varz = varx+vary
print(varz)
print(varz.grad_fn)

tensor([[-0.7317, -1.1116],
        [ 0.0369,  0.6772]], grad_fn=<AddBackward0>)


In [22]:
#SHOULD NOT try to re wrap the tensor with already wrapped tensor we will loose the gradients
new = autograd.Variable(varz.data)
print(new.data)
print(new.grad_fn)


tensor([[-0.7317, -1.1116],
        [ 0.0369,  0.6772]])
None
